# Generated by Django 5.0.7 on 2024-07-28 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_posts_publish_18b59a_idx',
            old_name='bloggy_post_publish_a4f15b_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 14, 51, 33, 548977, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
