# Generated by Django 5.0.7 on 2024-07-29 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0004_alter_post_publish_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 13, 11, 33, 555919, tzinfo=datetime.timezone.utc)),
        ),
    ]
