# Generated by Django 5.0.7 on 2024-07-31 08:44

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0006_post_tags_alter_post_publish'),
    ]

    operations = [
        TrigramExtension()
    ]
